steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/myrepo', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/myrepo']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ["run", "deploy", "mysvc", "--image", "gcr.io/${PROJECT_ID}/myrepo", "--port", "80", "--platform", "managed", "--region","us-central-1","--allow-unauthenticated"]
